#!/usr/bin/env sh
set -eu

ROOT=.
PKG_NAME=alumet-agent

if [ ! -d debian ]; then
    echo "This script must be executed in the \`deb\` directory"
    exit 1
fi
if [ ! -f alumet-agent ]; then
    echo "You must copy alumet-agent to this directory first"
    exit 1
fi

install -D -m 0755 ./alumet-agent                       "$ROOT/usr/lib/alumet-agent"
install -D -m 0755 ../rpm/SOURCES/alumet-agent-launcher "$ROOT/usr/bin/alumet-agent"
install -D -m 0644 ../rpm/SOURCES/alumet.service        "$ROOT/usr/lib/systemd/system/alumet.service"

# generate the configuration file and put it in the right folder with the right permissions
ALUMET_CONFIG="alumet-config.toml" ./alumet-agent --plugins csv,perf,procfs,socket-control config regen
install -D -m 0644 ./alumet-config.toml "$ROOT/etc/alumet/alumet-config.toml"

# generate the changelog
# NOTE: the version is determined from the changelog, not debian/control.
# It will end up in DEBIAN/control (generated by dpkg-buildpackage).
rm -f ./debian/changelog
DEBFULLNAME="Alumet maintainers" DEBEMAIL="maintainers@alumet.dev" \
dch --create --package "${PKG_NAME}" \
    --newversion "${PKG_VERSION}-${PKG_REVISION}" \
    --distribution UNRELEASED \
    --urgency medium \
    'Package update'

# Build the package, binary so we don't need to provide a source archive.
# The "nostrip" option prevents the debug symbols from being extracted into a separate package.
# With large binaries (agent compiled in debug mode, ~245MB), it's slower to build the package with nostrip.
DEB_BUILD_OPTIONS="nostrip" dpkg-buildpackage --build=binary -us -uc
